namespace FoodDrinkApp.Services;

public static class MockApiConfig
{
    // Replace this with the Resource endpoint generated by mockapi.io.
    // Example: https://682xxxx.mockapi.io/api/v1/foods
    public const string EndpointUrl = "https://6a1ce715bcc4f20d5ca3a89d.mockapi.io/foods";

    public static bool IsConfigured => !string.IsNullOrWhiteSpace(EndpointUrl);
}
